---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: client-go
  labels:
    app: client-go
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client-go
      task: client-go
  template:
    metadata:
      labels:
        app: client-go
        task: client-go
    spec:
      containers:
      - name: client-go
        image: pathcl/client-go:0.1.2
        resources:
          requests:
            memory: "128Mi"
        securityContext:
            runAsUser: 65532
